# Generated by Django 3.2.9 on 2021-11-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20211118_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº telefone celular'),
        ),
    ]
