# Generated by Django 3.2.9 on 2021-11-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_alter_empresa_telefone_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
