# Generated by Django 3.2.9 on 2021-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_alter_empresa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Razao Social da empresa'),
        ),
    ]
