# Generated by Django 3.2.9 on 2021-11-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='adverts', verbose_name='Upload de Imagem ou Video')),
            ],
        ),
    ]
