# Generated by Django 3.2.9 on 2021-11-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='tempo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
