# Generated by Django 3.2.9 on 2021-11-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_anuncios_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='tempo',
            field=models.TextField(verbose_name='Tempo de exibição em segundos'),
        ),
    ]
