# Generated by Django 3.2.9 on 2021-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_alter_empresa_telefone_responsavel'),
        ('adverts', '0003_alter_anuncios_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='Empresa',
            field=models.ManyToManyField(to='center.Empresa'),
        ),
    ]
