# Generated by Django 3.2.9 on 2021-11-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_alter_empresa_nome'),
        ('adverts', '0004_anuncios_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncios',
            name='Empresa',
        ),
        migrations.AddField(
            model_name='anuncios',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='center.empresa'),
            preserve_default=False,
        ),
    ]
