# Generated by Django 3.2.9 on 2021-11-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_rename_empresa_anuncios_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncios',
            old_name='nome',
            new_name='Empresa',
        ),
    ]
